---

- hosts: kafka1
  become: true
  tasks:

  # - name: Enable epel repo
  #   package:
  #     name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
  #     state: present
  
  - name: Add Confluent repository
    yum_repository:
      name: Confluent
      description: Confluent Repo for Kafka
      baseurl: https://packages.confluent.io/rpm/7.2
      gpgcheck: yes
      gpgkey: https://packages.confluent.io/rpm/7.2/archive.key
      enabled: yes


  - name: Install required software
    package:
      name: "{{ item }}"
      state: present
    loop: 
      - java-1.8.0-openjdk
      - firewalld
  
  - name: Start and enable firewalld
    systemd:
      name: firewalld
      state: started
      enabled: yes

  - name: Edit /etc/profile
    blockinfile:
      path: /etc/profile
      block: |
        export JAVA_HOME=/usr/lib/jvm/jre-1.8.0-openjdk
        export JRE_HOME=/usr/lib/jvm/jre
    register: java_vars

  - name: Source /etc/profile
    shell: source /etc/profile
    when: java_vars.changed

# https://docs.confluent.io/platform/current/installation/installing_cp/rhel-centos.html


  - name: Install Confluent Community
    package:
      name: confluent-community-2.13
      state: present

  - name: Edit /etc/hosts
    copy:
      dest: /etc/hosts
      content: |
        172.31.114.202 236d309b3a1c.mylabserver.com zoo1
        172.31.112.139 236d309b3a2c.mylabserver.com zoo2
        172.31.112.43 236d309b3a3c.mylabserver.com zoo3

  - name: Edit /etc/kafka/zookeeper.properties
    blockinfile:
      path: /etc/kafka/zookeeper.properties
      block: |
        tickTime=2000
        initLimit=5
        syncLimit=2
        server.1=zoo1:2888:3888
        server.2=zoo2:2888:3888
        server.3=zoo3:2888:3888
        autopurge.snapRetainCount=3
        autopurge.purgeInterval=24
    
  - name: Open port 2181, 2888, 3888, 9092
    firewalld:
      port: "{{ item }}"
      permanent: yes
      immediate: yes
      state: enabled
    loop:
      - 2181/tcp
      - 2888/tcp
      - 3888/tcp
      - 9092/tcp
  
  - name: zookeper ID file 1
    copy:
      dest: /var/lib/zookeeper/myid
      content: 1
    when: ansible_nodename == "236d309b3a1c.mylabserver.com"

  - name: zookeper ID file 2
    copy:
      dest: /var/lib/zookeeper/myid
      content: 2
    when: ansible_nodename == "236d309b3a2c.mylabserver.com"
  
  - name: zookeper ID file 3
    copy:
      dest: /var/lib/zookeeper/myid
      content: 3
    when: ansible_nodename == "236d309b3a3c.mylabserver.com"

  - name: Edit broker ID 1
    lineinfile:
      path: /etc/kafka/server.properties
      regexp: '^broker.id'
      line: broker.id=1
    when: ansible_nodename == "236d309b3a1c.mylabserver.com"

  - name: Edit broker ID 2
    lineinfile:
      path: /etc/kafka/server.properties
      regexp: '^broker.id'
      line: broker.id=2
    when: ansible_nodename == "236d309b3a2c.mylabserver.com"

  - name: Edit broker ID 3
    lineinfile:
      path: /etc/kafka/server.properties
      regexp: '^broker.id'
      line: broker.id=3
    when: ansible_nodename == "236d309b3a3c.mylabserver.com"

  - name: Edit zookeeper connect
    lineinfile:
      path: /etc/kafka/server.properties
      regexp: '^zookeeper.connect.+'
      line: zookeeper.connect=zoo1:2181

  - name: Edit listeners in kafka server properties in kafka1
    lineinfile:
      path: /etc/kafka/server.properties
      regexp: '^#listeners=PLAINTEXT://:9092'
      line: listeners=PLAINTEXT://236d309b3a1c.mylabserver.com:9092
    when: ansible_nodename == "236d309b3a1c.mylabserver.com"

  - name: Edit listeners in kafka server properties in kafka2
    lineinfile:
      path: /etc/kafka/server.properties
      regexp: '^#listeners=PLAINTEXT://:9092'
      line: listeners=PLAINTEXT://236d309b3a2c.mylabserver.com:9092
    when: ansible_nodename == "236d309b3a2c.mylabserver.com"

  - name: Edit listeners in kafka server properties in kafka3
    lineinfile:
      path: /etc/kafka/server.properties
      regexp: '^#listeners=PLAINTEXT://:9092'
      line: listeners=PLAINTEXT://236d309b3a3c.mylabserver.com:9092
    when: ansible_nodename == "236d309b3a3c.mylabserver.com"

  - name: Edit advertise listeners in kafka server properties in kafka1
    lineinfile:
      path: /etc/kafka/server.properties
      regexp: '^#listeners=PLAINTEXT://:9092'
      line: listeners=PLAINTEXT://236d309b3a1c.mylabserver.com:9092
    when: ansible_nodename == "236d309b3a1c.mylabserver.com"

  - name: Edit advertise listeners in kafka server properties in kafka2
    lineinfile:
      path: /etc/kafka/server.properties
      regexp: '^#advertised.listeners=.+'
      line: advertised.listeners=PLAINTEXT://236d309b3a2c.mylabserver.com:9092
    when: ansible_nodename == "236d309b3a2c.mylabserver.com"

  - name: Edit advertise listeners in kafka server properties in kafka3
    lineinfile:
      path: /etc/kafka/server.properties
      regexp: '^#advertised.listeners=.+'
      line: advertised.listeners=PLAINTEXT://236d309b3a3c.mylabserver.com:9092
    when: ansible_nodename == "236d309b3a3c.mylabserver.com"

  - name: Start confluent-zookeeper and confluent-kafka
    systemd:
      name: "{{ item }}"
      state: started
      enabled: yes
    loop:
      - confluent-zookeeper
      - confluent-kafka

- hosts: checkmk
  become: true
  tasks:

  - name: Install required software
    package:
      name: firewalld
      state: present

  - name: Start and enable firewalld
    systemd:
      name: firewalld
      state: started
      enabled: yes

  - name: Install checkmk
    package:
      name: https://download.checkmk.com/checkmk/2.1.0p9/check-mk-free-2.1.0p9-el7-38.x86_64.rpm
      state: present

  - name: Start checkmk service
    systemd:
      name: omd
      state: started
      enabled: yes

  - name: Allow http traffic for checkmk
    firewalld:
      zone: public
      service: http
      permanent: yes
      immediate: yes
      state: enabled

  - name: Set httpd_can_network_connect flag on and keep it persistent across reboots
    seboolean:
      name: httpd_can_network_connect
      state: yes
      persistent: yes
