---

- hosts: kafka2
  become: true
  tasks:

  - name: Install java-1.8.0-openjdk
    package:
      name: java-1.8.0-openjdk
      state: present

  - name: Edit /etc/profile
    blockinfile:
      path: /etc/profile
      block: |
        export JAVA_HOME=/usr/lib/jvm/jre-1.8.0-openjdk
        export JRE_HOME=/usr/lib/jvm/jre
    register: java_vars

  - name: Source /etc/profile
    shell: source /etc/profile
    when: java_vars.changed

# https://docs.confluent.io/platform/current/installation/installing_cp/rhel-centos.html

  - name: Add Confluent repository
    yum_repository:
      name: Confluent
      description: Confluent Repo for Kafka
      baseurl: https://packages.confluent.io/rpm/7.2
      gpgcheck: yes
      gpgkey: https://packages.confluent.io/rpm/7.2/archive.key
      enabled: yes


  
  